server:
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
  port: 8888
  shutdown: graceful

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Manipay/config-repo
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s